- name: create ansible group
  group:
    name: ansible
    state: present
    gid: 200

- name: Create the ansible user
  user:
    name: ansible
    comment: ansible
    group: ansible
    uid: 200
    state: present

- name: setup ssh keys
  copy:
    src: '{{item.name}}'
    dest: /home/ansible/.ssh
    owner: ansible
    group: ansible
  with_items:
    - { name: 'id_rsa', mode: '0600'}
    - { name: 'id_rsa.pub', mode: '0644'}

- name: add ansible authorized key
  authorized_key:
    user: ansible
    state: present
    key: "{{lookup('file', 'id_rsa.pub')}}"
  when: not control_server