---
- name: Setup Zabbix
  hosts: localhost

  tasks:
    - name: Set credentials to access Zabbix Server API
      ansible.builtin.set_fact:
        ansible_user: Admin
        ansible_username: Admin
        ansible_httpapi_pass: zabbix
        ansible_network_os: community.zabbix.zabbix
        ansible_connection: httpapi
        ansible_httpapi_port: 8080
        ansible_httpapi_use_ssl: false
        ansible_httpapi_validate_certs: false
        ansible_zabbix_url_path: ''  # If Zabbix WebUI runs on non-default (zabbix) path ,e.g. http://<FQDN>/zabbixeu
        ansible_host: localhost

    - name: Retrieve API information
      # set task level variables as we change ansible_connection plugin here
      community.zabbix.zabbix_api_info:
      register: zbx_api_info

    - name: Create Template
      zabbix_template:
#        template_name: "Template Webapps"
        template_json: "{{ lookup('file', 'web_apps_template.json') }}"
        state: present

    - name: Create Hosts
      zabbix_host:
        host_name: '{{item.hostname}}'
        visible_name: "{{item.visible}}"
        host_groups:
          - Linux servers
        status: enabled
        state: present
        inventory_mode: manual
        link_templates:
          - Template Webapps

      with_items:
        - {hostname: "webapp1", visible: "web-app-1"}
        - {hostname: "webapp2", visible: "web-app-2"}